In [1]:
# Make device agnostic code
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./binary_class_data.csv')

In [4]:
df.drop(columns = ['neo_id', 'name'], inplace = True)

In [5]:
def binary_class_fn(data):
    if data == True:
        data  = 1
    elif data == False:
        data = 0
    return data
df['is_hazardous'] = df['is_hazardous'].map(lambda x : binary_class_fn(x)) 

#df['is_hazardous'] = df['is_hazardous'].replace({True: 1, False : 0})

In [6]:
df

absolute_magnitude  estimated_diameter_min  estimated_diameter_max  \
0                   19.140                0.394962                0.883161   
1                   18.500                0.530341                1.185878   
2                   21.450                0.136319                0.304818   
3                   20.630                0.198863                0.444672   
4                   22.700                0.076658                0.171412   
...                    ...                     ...                     ...   
338194              28.580                0.005112                0.011430   
338195              28.690                0.004859                0.010865   
338196              21.919                0.109839                0.245607   
338197              23.887                0.044377                0.099229   
338198              22.951                0.068290                0.152700   

       orbiting_body  relative_velocity  miss_distance  is_hazardous  
0              Earth       71745.401048   5.814362e+07             0  
1              Earth      109949.757148   5.580105e+07             1  
2              Earth       24865.506798   6.720689e+07             0  
3              Earth       78890.076805   3.039644e+07             0  
4              Earth       56036.519484   6.311863e+07             0  
...              ...                ...            ...           ...  
338194         Earth       56646.985988   6.406548e+07             0  
338195         Earth       21130.768947   2.948883e+07             0  
338196         Earth       11832.041031   5.346078e+07             0  
338197         Earth       56198.382733   5.184742e+06             0  
338198         Earth       42060.357830   7.126682e+06             0  

[338199 rows x 7 columns]

In [7]:
df.drop(columns = ['orbiting_body'], inplace = True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 338199 entries, 0 to 338198
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   absolute_magnitude      338171 non-null  float64
 1   estimated_diameter_min  338171 non-null  float64
 2   estimated_diameter_max  338171 non-null  float64
 3   relative_velocity       338199 non-null  float64
 4   miss_distance           338199 non-null  float64
 5   is_hazardous            338199 non-null  int64  
dtypes: float64(5), int64(1)
memory usage: 15.5 MB


In [9]:
X = df.iloc[:100, :-1]
y = df.iloc[:100, -1]
X = X.to_numpy()
y = y.to_numpy()

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X= scaler.fit_transform(X)

In [11]:
X

array([[0.18301611, 0.31495802, 0.31495802, 0.58237566, 0.75923667],
       [0.13616398, 0.4235511 , 0.4235511 , 0.94903008, 0.72535006],
       [0.35212299, 0.10748974, 0.10748974, 0.13246047, 0.89034165],
       [0.2920937 , 0.15765957, 0.15765957, 0.65094446, 0.35785883],
       [0.44363104, 0.0596332 , 0.0596332 , 0.43161456, 0.83120276],
       [0.61200586, 0.01946394, 0.01946394, 0.34947348, 0.5388049 ],
       [0.35578331, 0.1050007 , 0.1050007 , 0.4490505 , 0.3127645 ],
       [0.22767204, 0.23736757, 0.23736756, 0.34462533, 0.93039736],
       [0.3704246 , 0.09559839, 0.09559839, 0.25299196, 0.        ],
       [0.49853587, 0.04167474, 0.04167474, 0.26355194, 0.81012008],
       [0.68667643, 0.01147228, 0.01147228, 0.32690053, 0.41322478],
       [0.35578331, 0.1050007 , 0.1050007 , 0.44905051, 0.31276449],
       [0.52122987, 0.03588336, 0.03588336, 0.07733257, 0.09817356],
       [0.00512445, 0.96821895, 0.96821895, 0.01574217, 0.92480644],
       [0.56076135, 0.02757407, 0.

In [12]:
y.shape

(100,)

In [13]:
import torch
X = torch.tensor(X).type(torch.float)
y = torch.tensor(y).type(torch.float)

In [14]:
X,y

(tensor([[0.1830, 0.3150, 0.3150, 0.5824, 0.7592],
         [0.1362, 0.4236, 0.4236, 0.9490, 0.7254],
         [0.3521, 0.1075, 0.1075, 0.1325, 0.8903],
         [0.2921, 0.1577, 0.1577, 0.6509, 0.3579],
         [0.4436, 0.0596, 0.0596, 0.4316, 0.8312],
         [0.6120, 0.0195, 0.0195, 0.3495, 0.5388],
         [0.3558, 0.1050, 0.1050, 0.4491, 0.3128],
         [0.2277, 0.2374, 0.2374, 0.3446, 0.9304],
         [0.3704, 0.0956, 0.0956, 0.2530, 0.0000],
         [0.4985, 0.0417, 0.0417, 0.2636, 0.8101],
         [0.6867, 0.0115, 0.0115, 0.3269, 0.4132],
         [0.3558, 0.1050, 0.1050, 0.4491, 0.3128],
         [0.5212, 0.0359, 0.0359, 0.0773, 0.0982],
         [0.0051, 0.9682, 0.9682, 0.0157, 0.9248],
         [0.5608, 0.0276, 0.0276, 0.5448, 0.9497],
         [0.5622, 0.0273, 0.0273, 0.3273, 0.5021],
         [0.6047, 0.0205, 0.0205, 0.2800, 0.0726],
         [0.3719, 0.0947, 0.0947, 0.1962, 0.5475],
         [0.0527, 0.7173, 0.7173, 0.8517, 0.7166],
         [0.1940, 0.2938, 0.293

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
print(f'X Train Shape: {X_train.shape}')
print(f'X Test Shape: {X_test.shape}')
print(f'y Train Shape: {y_train.shape}')
print(f'y Test Shape: {y_test.shape}')

X Train Shape: torch.Size([80, 5])
X Test Shape: torch.Size([20, 5])
y Train Shape: torch.Size([80])
y Test Shape: torch.Size([20])


In [17]:
from torch.utils.data import Dataset, DataLoader
class CustomDataSet(Dataset):
    def __init__(self, x_data, y_data):
        super().__init__()
        #self.x = torch.tensor(x_data, dtype = torch.float32)
        #self.y = torch.tensor(y_data, dtype = torch.float32)
        self.x = x_data
        self.y = y_data
        self.x = self.x.to(device)
        self.y = self.y.to(device)
    def device_type(self):
        return self.x.device
    def __len__(self):
        return len(self.x)
    def __getitem__(self, index):
        return self.x[index], self.y[index]

In [18]:
dataset_train = CustomDataSet(X_train, y_train)
dataset_test = CustomDataSet(X_test, y_test)

In [19]:
dataset_train.device_type()

device(type='cuda', index=0)

In [20]:
dataloader_train = DataLoader(dataset_train, batch_size=8, shuffle=True)
# for X_batch, y_batch in dataloader:
#     print(X_batch, y_batch)
#     break
    
dataloader_test = DataLoader(dataset_test, batch_size = 8, shuffle = True)

In [21]:
#y_train = y_train.unsqueeze(dim = 1)
X_train, y_train

(tensor([[0.6933, 0.0109, 0.0109, 0.0896, 0.3808],
         [0.4473, 0.0582, 0.0582, 0.2462, 0.7831],
         [0.1515, 0.3843, 0.3843, 0.6772, 0.4645],
         [0.5146, 0.0375, 0.0375, 0.1041, 0.9510],
         [0.7013, 0.0103, 0.0103, 0.6309, 0.8002],
         [0.5622, 0.0273, 0.0273, 0.3273, 0.5021],
         [0.1859, 0.3092, 0.3092, 0.5494, 0.4665],
         [0.3243, 0.1284, 0.1284, 0.2087, 0.2984],
         [0.4985, 0.0417, 0.0417, 0.2636, 0.8101],
         [0.3492, 0.1095, 0.1095, 0.4194, 0.3302],
         [0.3558, 0.1050, 0.1050, 0.4491, 0.3128],
         [0.3880, 0.0854, 0.0854, 0.2702, 0.5340],
         [0.1567, 0.3721, 0.3721, 0.7460, 0.9833],
         [0.3924, 0.0830, 0.0830, 0.3119, 0.1932],
         [0.0000, 1.0000, 1.0000, 0.1259, 0.5231],
         [0.6120, 0.0195, 0.0195, 0.3495, 0.5388],
         [0.1903, 0.3007, 0.3007, 0.2969, 0.9085],
         [0.4510, 0.0569, 0.0569, 0.1575, 0.1242],
         [0.2731, 0.1779, 0.1779, 0.1054, 0.8395],
         [0.6047, 0.0205, 0.020

In [22]:
#y_test = y_test.unsqueeze(dim = 1)

In [23]:
from torch import nn
class LogisticRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(in_features=5, out_features=20)
        self.layer2 = nn.Linear(in_features=20, out_features=20) # extra layer
        self.layer3 = nn.Linear(in_features=20, out_features=1)
        self.relu = nn.ReLU()
    def forward(self, x):
        x1 = self.relu(self.layer1(x))
        x2 = self.relu(self.layer2(x1))
        x3 = self.layer3(x2)
        return x3, x2, x1
        #return self.layer3(self.layer2(self.layer1(x)))
model_0 = LogisticRegressionModel().to(device)
#model_0 = LogisticRegressionModel()

In [24]:
model_0.state_dict()

OrderedDict([('layer1.weight',
              tensor([[-0.2902, -0.2872,  0.1404,  0.3569,  0.0564],
                      [ 0.2362, -0.0446,  0.0901,  0.3114, -0.3530],
                      [ 0.1450,  0.0668, -0.3662,  0.4277, -0.1040],
                      [ 0.4046,  0.3439, -0.3670,  0.1278, -0.1741],
                      [ 0.1255,  0.0947, -0.4156, -0.1861, -0.0155],
                      [ 0.1962,  0.3179,  0.3994, -0.1566,  0.1652],
                      [ 0.4466,  0.2171, -0.3128,  0.0333, -0.2905],
                      [ 0.2404,  0.0020,  0.1273, -0.2882, -0.1837],
                      [-0.2729,  0.3109, -0.1137, -0.1642, -0.0286],
                      [ 0.3923, -0.0540, -0.3418, -0.2726, -0.1608],
                      [-0.2874, -0.0781, -0.2815, -0.3904, -0.1399],
                      [-0.2019, -0.1941, -0.4326, -0.1611,  0.3952],
                      [ 0.4067,  0.0770,  0.2513,  0.2910, -0.3411],
                      [-0.3611, -0.3985, -0.1793, -0.2564, -0.2293],
   

In [25]:
model_0.parameters

<bound method Module.parameters of LogisticRegressionModel(
  (layer1): Linear(in_features=5, out_features=20, bias=True)
  (layer2): Linear(in_features=20, out_features=20, bias=True)
  (layer3): Linear(in_features=20, out_features=1, bias=True)
  (relu): ReLU()
)>

In [26]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(params=model_0.parameters(), 
                            lr=0.0001)

In [27]:
# Calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item() # torch.eq() calculates where two tensors are equal
    acc = (correct / len(y_pred)) * 100 
    return acc

In [28]:
# X_train = X_train.to(device)
# X_test = X_test.to(device)
# y_train = y_train.to(device)
# y_test = y_test.to(device)
#dataloader_train = dataloader_train.to(device)
#dataloader_test = dataloader_test.to(device)

In [29]:
y_train.shape
y_test.shape

torch.Size([20])

In [30]:
# #Building our training loop
# epoch_count = []
# test_loss_list = []
# train_loss_list = []
# y_logits_data = []
# y_train_data = []
# for epoch in range(100):
#     model_0.train()
#     for X_train_batch, y_train_batch in dataloader_train:
#         y_logits = model_0(X_train_batch).squeeze()
#         y_logits_data.append(y_logits)
#         y_pred = torch.round(torch.sigmoid(y_logits))
#         #print(y_train.squeeze().shape)
#         y_train = y_train.squeeze()
#         loss = loss_fn(y_logits, y_train_batch)
#         y_train_data.append(y_train)
#         acc = accuracy_fn(y_true=y_train_batch, y_pred=y_pred)
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()
#     #Testing the model
#     model_0.eval()
#     with torch.inference_mode():
#         for X_test_batch, y_test_batch in dataloader_test:
#             test_logits = model_0(X_test_batch).squeeze()
#             y_test_pred = torch.round(torch.sigmoid(test_logits))
#             y_test = y_test.squeeze()
#             test_loss = loss_fn(test_logits, y_test_batch)
#             test_acc = accuracy_fn(y_test_batch, y_test_pred)
#     if epoch % 10 == 0:
#         print(f"Epoch: {epoch} | Loss: {loss:.5f}, Accuracy: {acc:.2f}% | Test loss: {test_loss:.5f}, Test acc: {test_acc:.2f}%")
                 

In [31]:
epoch_count = []
test_loss_list = []
train_loss_list = []
x1_dim_list = []
x2_dim_list= []
x3_dim_list = []
for epoch in range(100):
    model_0.train()
    epoch_train_loss = 0
    epoch_train_acc = 0
    for X_train_batch, y_train_batch in dataloader_train:
        y_logits, x2, x1 = model_0(X_train_batch)
        while len(x2_dim_list) < 1:
            x2_dim_list.append(x2)
            x1_dim_list.append(x1)
        y_logits = y_logits.squeeze()
        y_pred = torch.round(torch.sigmoid(y_logits))
        loss = loss_fn(y_logits, y_train_batch)
        acc = accuracy_fn(y_true=y_train_batch, y_pred=y_pred)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        epoch_train_loss += loss.item()
        epoch_train_acc += acc

    # Calculate average loss and accuracy over all batches
    avg_train_loss = epoch_train_loss / dataloader_train.__len__()
    avg_train_acc = epoch_train_acc / dataloader_train.__len__()

    model_0.eval()
    epoch_test_loss = 0
    epoch_test_acc = 0
    with torch.inference_mode():
        for X_test_batch, y_test_batch in dataloader_test:
            test_logits, _, __ = model_0(X_test_batch)
            test_logits = test_logits.squeeze()
            y_test_pred = torch.round(torch.sigmoid(test_logits))
            
            test_loss = loss_fn(test_logits, y_test_batch)
            test_acc = accuracy_fn(y_true=y_test_batch, y_pred=y_test_pred)

            epoch_test_loss += test_loss.item()
            epoch_test_acc += test_acc

    avg_test_loss = epoch_test_loss / dataloader_test.__len__()
    avg_test_acc = epoch_test_acc / dataloader_test.__len__()

    epoch_count.append(epoch)
    train_loss_list.append(avg_train_loss)
    test_loss_list.append(avg_test_loss)

    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Train Loss: {avg_train_loss:.5f}, Train Accuracy: {avg_train_acc:.2f}% | Test Loss: {avg_test_loss:.5f}, Test Accuracy: {avg_test_acc:.2f}%")


Epoch: 0 | Train Loss: 0.60018, Train Accuracy: 87.50% | Test Loss: 0.61787, Test Accuracy: 79.17%
Epoch: 10 | Train Loss: 0.58079, Train Accuracy: 87.50% | Test Loss: 0.60506, Test Accuracy: 79.17%
Epoch: 20 | Train Loss: 0.56186, Train Accuracy: 87.50% | Test Loss: 0.60662, Test Accuracy: 75.00%
Epoch: 30 | Train Loss: 0.54213, Train Accuracy: 87.50% | Test Loss: 0.57725, Test Accuracy: 79.17%
Epoch: 40 | Train Loss: 0.51988, Train Accuracy: 87.50% | Test Loss: 0.58463, Test Accuracy: 75.00%
Epoch: 50 | Train Loss: 0.49574, Train Accuracy: 87.50% | Test Loss: 0.54714, Test Accuracy: 79.17%
Epoch: 60 | Train Loss: 0.47204, Train Accuracy: 87.50% | Test Loss: 0.59574, Test Accuracy: 70.83%
Epoch: 70 | Train Loss: 0.44945, Train Accuracy: 87.50% | Test Loss: 0.52228, Test Accuracy: 79.17%
Epoch: 80 | Train Loss: 0.42953, Train Accuracy: 87.50% | Test Loss: 0.51418, Test Accuracy: 79.17%
Epoch: 90 | Train Loss: 0.41282, Train Accuracy: 87.50% | Test Loss: 0.50854, Test Accuracy: 79.17%


In [32]:
# pred = y_logits_data[0]
# tar = y_train_data[0]

In [33]:
# loss1 = nn.BCEWithLogitsLoss()
# predicted = torch.tensor([0.546, 0.423, 0.123], dtype=torch.float32)
# target = torch.tensor([1, 0, 1], dtype=torch.float32)
# test_loss = loss1(pred, tar)
# print(test_loss)

In [34]:
x2_dim_list

[tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3548, 0.1769, 0.0000,
          0.0000, 0.0000, 0.0000, 0.2830, 0.2167, 0.2055, 0.0000, 0.0401, 0.0000,
          0.3506, 0.3066],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3870, 0.1827, 0.0000,
          0.0000, 0.0000, 0.0000, 0.3109, 0.2283, 0.2176, 0.0000, 0.0463, 0.0000,
          0.3403, 0.2891],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3569, 0.1899, 0.0000,
          0.0000, 0.0000, 0.0000, 0.2949, 0.2234, 0.2132, 0.0000, 0.0277, 0.0000,
          0.3672, 0.3159],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3806, 0.1899, 0.0000,
          0.0000, 0.0000, 0.0000, 0.3167, 0.2260, 0.2225, 0.0000, 0.0442, 0.0000,
          0.3429, 0.2847],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3845, 0.2034, 0.0000,
          0.0000, 0.0000, 0.0000, 0.3283, 0.2232, 0.2278, 0.0000, 0.0469, 0.0000,
          0.3436, 0.2734],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0

In [35]:
x2_dim_list[0]

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3548, 0.1769, 0.0000,
         0.0000, 0.0000, 0.0000, 0.2830, 0.2167, 0.2055, 0.0000, 0.0401, 0.0000,
         0.3506, 0.3066],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3870, 0.1827, 0.0000,
         0.0000, 0.0000, 0.0000, 0.3109, 0.2283, 0.2176, 0.0000, 0.0463, 0.0000,
         0.3403, 0.2891],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3569, 0.1899, 0.0000,
         0.0000, 0.0000, 0.0000, 0.2949, 0.2234, 0.2132, 0.0000, 0.0277, 0.0000,
         0.3672, 0.3159],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3806, 0.1899, 0.0000,
         0.0000, 0.0000, 0.0000, 0.3167, 0.2260, 0.2225, 0.0000, 0.0442, 0.0000,
         0.3429, 0.2847],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3845, 0.2034, 0.0000,
         0.0000, 0.0000, 0.0000, 0.3283, 0.2232, 0.2278, 0.0000, 0.0469, 0.0000,
         0.3436, 0.2734],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3

In [36]:
#2500, 32, 20

In [37]:
#125,8,20